#!/usr/bin/env python
# encoding: utf-8

import boards

def build(bld):
    vehicle = bld.path.name

    bld.ap_stlib(
        name=vehicle + '_libs',
        ap_vehicle=vehicle,
        ap_libraries=[
            'AP_NavEKF3',
            'AP_NavEKF',
            'AP_Common',
            'AP_Math',
            'AP_DAL',
            'AP_InternalError',
            'AP_Declination',
            'AP_RTC',
        ],
    )

    bld.ap_example(
        use=vehicle + '_libs',
        defines=['HAL_NO_GCS=1'],
    )
