#!/usr/bin/env python
# encoding: utf-8

def configure(cfg):
    cfg.env.DISABLE_SCRIPTING = 1

def build(bld):
    bld.ap_stlib(
        name='AP_DAL' + '_libs',
        ap_vehicle='AP_DAL_Standalone',
        ap_libraries=[
            'AP_NavEKF3',
            'AP_NavEKF',
            'AP_Common',
            'AP_Math',
            'AP_DAL',
            'AP_InternalError',
            'AP_Declination',
            'AP_RTC',
        ],
    )
    bld.env.CXXFLAGS += '-DHAL_NO_GCS=1',

    bld.ap_program(
        program_groups=['examples'],
        use='AP_DAL_libs',
    )
