// auto-generated DMA mapping from dma_resolver.py
#define STM32_ADC_ADC1_DMA_STREAM      STM32_DMA_STREAM_ID(2, 4)
#define STM32_I2C_I2C1_RX_DMA_STREAM   STM32_DMA_STREAM_ID(1, 0)
#define STM32_I2C_I2C1_TX_DMA_STREAM   STM32_DMA_STREAM_ID(1, 1)
#define STM32_I2C_I2C2_RX_DMA_STREAM   STM32_DMA_STREAM_ID(1, 2)
#define STM32_I2C_I2C2_TX_DMA_STREAM   STM32_DMA_STREAM_ID(1, 7)
#define STM32_SPI_SPI1_RX_DMA_STREAM   STM32_DMA_STREAM_ID(2, 0)
#define STM32_SPI_SPI1_TX_DMA_STREAM   STM32_DMA_STREAM_ID(2, 3)
#define STM32_SPI_SPI2_RX_DMA_STREAM   STM32_DMA_STREAM_ID(1, 3)
#define STM32_SPI_SPI2_TX_DMA_STREAM   STM32_DMA_STREAM_ID(1, 4)
#define STM32_UART_USART1_RX_DMA_STREAM STM32_DMA_STREAM_ID(2, 2)
#define STM32_UART_USART1_TX_DMA_STREAM STM32_DMA_STREAM_ID(2, 7)
#define STM32_UART_USART2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_UART_USART2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_UART_USART6_RX_DMA_STREAM STM32_DMA_STREAM_ID(2, 1)
#define STM32_UART_USART6_TX_DMA_STREAM STM32_DMA_STREAM_ID(2, 6)


// generated UART configuration lines
#define USART1_CONFIG { (BaseSequentialStream*) &SD1, false, true, STM32_UART_USART1_RX_DMA_STREAM, STM32_USART1_RX_DMA_CHN, true, STM32_UART_USART1_TX_DMA_STREAM, STM32_USART1_TX_DMA_CHN}
#define USART2_CONFIG { (BaseSequentialStream*) &SD2, false, true, STM32_UART_USART2_RX_DMA_STREAM, STM32_USART2_RX_DMA_CHN, true, STM32_UART_USART2_TX_DMA_STREAM, STM32_USART2_TX_DMA_CHN}
#define USART6_CONFIG { (BaseSequentialStream*) &SD6, false, true, STM32_UART_USART6_RX_DMA_STREAM, STM32_USART6_RX_DMA_CHN, true, STM32_UART_USART6_TX_DMA_STREAM, STM32_USART6_TX_DMA_CHN}
