// auto-generated DMA mapping from dma_resolver.py

// Note: The following peripherals can't be resolved for DMA: ['UART8_RX', 'UART7_TX', 'UART7_RX']
#define STM32_ADC_ADC1_DMA_STREAM      STM32_DMA_STREAM_ID(2, 4)
#define STM32_I2C_I2C1_RX_DMA_STREAM   STM32_DMA_STREAM_ID(1, 0) // shared I2C1_RX,UART8_TX
#define STM32_I2C_I2C1_TX_DMA_STREAM   STM32_DMA_STREAM_ID(1, 7)
#define STM32_SDC_SDIO_DMA_STREAM      STM32_DMA_STREAM_ID(2, 6)
#define STM32_SPI_SPI1_RX_DMA_STREAM   STM32_DMA_STREAM_ID(2, 0)
#define STM32_SPI_SPI1_TX_DMA_STREAM   STM32_DMA_STREAM_ID(2, 5)
#define STM32_SPI_SPI2_RX_DMA_STREAM   STM32_DMA_STREAM_ID(1, 3) // shared SPI2_RX,USART3_TX
#define STM32_SPI_SPI2_TX_DMA_STREAM   STM32_DMA_STREAM_ID(1, 4) // shared UART4_TX,SPI2_TX
#define STM32_SPI_SPI4_RX_DMA_STREAM   STM32_DMA_STREAM_ID(2, 3)
#define STM32_SPI_SPI4_TX_DMA_STREAM   STM32_DMA_STREAM_ID(2, 1)
#define STM32_UART_UART4_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 2)
#define STM32_UART_UART4_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 4) // shared UART4_TX,SPI2_TX
#define STM32_UART_UART8_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 0) // shared I2C1_RX,UART8_TX
#define STM32_UART_USART2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
#define STM32_UART_USART2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)
#define STM32_UART_USART3_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 1)
#define STM32_UART_USART3_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 3) // shared SPI2_RX,USART3_TX
#define STM32_UART_USART6_RX_DMA_STREAM STM32_DMA_STREAM_ID(2, 2)
#define STM32_UART_USART6_TX_DMA_STREAM STM32_DMA_STREAM_ID(2, 7)


// generated UART configuration lines
#define USART2_CONFIG { (BaseSequentialStream*) &SD2, false, true, STM32_UART_USART2_RX_DMA_STREAM, STM32_USART2_RX_DMA_CHN, true, STM32_UART_USART2_TX_DMA_STREAM, STM32_USART2_TX_DMA_CHN}
#define USART3_CONFIG { (BaseSequentialStream*) &SD3, false, true, STM32_UART_USART3_RX_DMA_STREAM, STM32_USART3_RX_DMA_CHN, true, STM32_UART_USART3_TX_DMA_STREAM, STM32_USART3_TX_DMA_CHN}
#define UART4_CONFIG { (BaseSequentialStream*) &SD4, false, true, STM32_UART_UART4_RX_DMA_STREAM, STM32_UART4_RX_DMA_CHN, true, STM32_UART_UART4_TX_DMA_STREAM, STM32_UART4_TX_DMA_CHN}
#define USART6_CONFIG { (BaseSequentialStream*) &SD6, false, true, STM32_UART_USART6_RX_DMA_STREAM, STM32_USART6_RX_DMA_CHN, true, STM32_UART_USART6_TX_DMA_STREAM, STM32_USART6_TX_DMA_CHN}
#define UART7_CONFIG { (BaseSequentialStream*) &SD7, false, false, 0, 0, false, 0, 0}
#define UART8_CONFIG { (BaseSequentialStream*) &SD8, false, false, 0, 0, true, STM32_UART_UART8_TX_DMA_STREAM, STM32_UART8_TX_DMA_CHN}
